### ISSUE TITLE
web server error

### ISSUE THREAD

**Issue by Alex-Songs** [kyutai-labs/moshi#92] opened 2024-09-21 00:33 UTC
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The PyTorch implementation

### Question

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addModule')
    at index-ClFQVzk0.js:431:71092
    at index-ClFQVzk0.js:431:71260
    at onClick (index-ClFQVzk0.js:431:73819)
    at Object.Nb (index-ClFQVzk0.js:37:9852)
    at Tb (index-ClFQVzk0.js:37:10006)
    at Ub (index-ClFQVzk0.js:37:10063)
    at nf (index-ClFQVzk0.js:37:31422)
    at se (index-ClFQVzk0.js:37:31839)
    at index-ClFQVzk0.js:37:36991
    at Qk (index-ClFQVzk0.js:40:36798)

**Comment by LaurentMazare** [comment] 2024-09-23 12:21
Duplicate of #86 , this is likely caused by connecting to a remote server via http which disables audio. The easy fix is to tunnel the 8998 port from the remote server to localhost and the connect normally to http://localhost:8998 . I'll tweak the faq to make these instructions more clear.

**Closed by LaurentMazare** 2024-09-23 12:21 UTC
Labels: question
